pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install .NET Core 3'
  inputs:
    version: '3.0.100-preview3-010431'

- script: dotnet test --logger "trx;LogFileName=IndexBrowser.trx"
  displayName: 'Build and Test'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
